package com.masjid.crm.dto.response;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.masjid.crm.model.FinancialCategory;
import com.masjid.crm.model.FinancialSource;
import com.masjid.crm.model.PaymentMethod;
import com.masjid.crm.model.PaymentStatus;
import com.masjid.crm.model.TransactionType;
import lombok.Builder;
import lombok.Data;

import java.util.Date;

@Data
@Builder
public class FinancialAccountResponse {

    private Long id;

    private TransactionType transactionType;

    private FinancialCategory category;

    private Double amount;

    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date transactionDate;

    private PaymentMethod paymentMethod;

    private String referenceNumber;

    private String payerOrPayeeName;

    private String description;

    private FinancialSource sourceType;

    private Long sourceId;

    private boolean autoGenerated;

    private PaymentStatus paymentStatus;
}
