package com.masjid.crm.Util;

import com.masjid.crm.dto.response.FinancialAccountListResponse;
import com.masjid.crm.dto.response.FinancialAccountResponse;
import com.masjid.crm.entity.FinancialAccount;
import com.masjid.crm.model.FinancialSource;
import org.springframework.data.domain.Page;

import java.util.List;
import java.util.stream.Collectors;

public class FinancialAccountFactory {

    public static FinancialAccountResponse toResponse(FinancialAccount entity) {
        FinancialSource source = entity.getSourceType();
        boolean autoGenerated = source != null && source != FinancialSource.MANUAL;
        return FinancialAccountResponse.builder()
                .id(entity.getId())
                .transactionType(entity.getTransactionType())
                .category(entity.getCategory())
                .amount(entity.getAmount())
                .transactionDate(entity.getTransactionDate())
                .paymentMethod(entity.getPaymentMethod())
                .referenceNumber(entity.getReferenceNumber())
                .payerOrPayeeName(entity.getPayerOrPayeeName())
                .description(entity.getDescription())
                .sourceType(source)
                .sourceId(entity.getSourceId())
                .autoGenerated(autoGenerated)
                .paymentStatus(entity.getPaymentStatus())
                .build();
    }

    public static FinancialAccountListResponse toListResponse(Page<FinancialAccount> page, Long count) {
        List<FinancialAccountResponse> responses = page.stream()
                .map(FinancialAccountFactory::toResponse)
                .collect(Collectors.toList());
        return FinancialAccountListResponse.builder()
                .transactions(responses)
                .count(count)
                .build();
    }
}
