server:
  port: 8313
  servlet.context-path: /mosque-way

spring:
  datasource:
    url: jdbc:postgresql://13.234.162.226:5432/mosque_way
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mosqueway
    hikari:
      maximum-pool-size: 10

  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
    hibernate.ddl-auto: update

jwt:
  expiration: 43200
  secret : masjidcrm