server:
  port: 8080
  servlet:
    context-path: /mosque-way

spring:
  datasource:
    url: jdbc:postgresql://test.mykarehealth.com:5432/masjid_crm_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: doctune
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
      keepalive-time: 30000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com.zaxxer.hikari: DEBUG

jwt:
  expiration: 43200
  secret: 23234234