INSERT INTO permission(id, permission) VALUES (1, 'ASSOCIATE_VIEW');
INSERT INTO permission(id, permission) VALUES (2, 'SUMMARY_VIEW');
INSERT INTO permission(id, permission) VALUES (3, 'LEADS_REPORT_BUTTON');
INSERT INTO permission(id, permission) VALUES (4, 'LEADS_PHONE_NUMBER_FIELD');
INSERT INTO permission(id, permission) VALUES (5, 'LEADS_ASSIGNED_FIELD');
INSERT INTO permission(id, permission) VALUES (6, 'LEADS_ORIGIN_FIELD');
INSERT INTO permission(id, permission) VALUES (7, 'LEADS_PARTNERSHIP_STATISTICS');
INSERT INTO permission(id, permission) VALUES (8, 'STATISTICS_ASSIGNED_FIELD');
INSERT INTO permission(id, permission) VALUES (9, 'HOSPITAL_ADD');
INSERT INTO permission(id, permission) VALUES (10, 'HOSPITAL_VIEW');
INSERT INTO permission(id, permission) VALUES (11, 'HOSPITAL_DELETE');
INSERT INTO permission(id, permission) VALUES (12, 'DOCTOR_ADD');
INSERT INTO permission(id, permission) VALUES (13, 'DOCTOR_VIEW');
INSERT INTO permission(id, permission) VALUES (14, 'DOCTOR_DELETE');
INSERT INTO permission(id, permission) VALUES (15, 'IP_OP_ASSIGNED_FIELD');
INSERT INTO permission(id, permission) VALUES (16, 'IP_OP_REPORT_BUTTON');
INSERT INTO permission(id, permission) VALUES (17, 'BULK_MESSAGE_TAB');
INSERT INTO permission(id, permission) VALUES (18, 'PARTNERSHIP_TAB');
INSERT INTO permission(id, permission) VALUES (19, 'IP_OP_TAB');
INSERT INTO permission(id, permission) VALUES (20, 'PC_TAB');
INSERT INTO permission(id, permission) VALUES (21, 'SMO_TAB');
INSERT INTO permission(id, permission) VALUES (22, 'ADD_ON_TAB');
INSERT INTO permission(id, permission) VALUES (23, 'STATISTICS_TAB');
INSERT INTO permission(id, permission) VALUES (24, 'ENQUIRY_UPDATE_SUB_TAB');
INSERT INTO permission(id, permission) VALUES (25, 'APPOINTMENTS_SUB_TAB');
INSERT INTO permission(id, permission) VALUES (26, 'HOSPITAL_TAB');
INSERT INTO permission(id, permission) VALUES (27, 'DOCTOR_TAB');
INSERT INTO permission(id, permission) VALUES (28, 'LEADS_ADD_BUTTON');
INSERT INTO permission(id, permission) VALUES (29, 'STATISTICS_TAB');
INSERT INTO permission(id, permission) VALUES (30, 'SETTINGS_TAB');
INSERT INTO permission(id, permission) VALUES (31, 'KARECHAT_TAB');
INSERT INTO permission(id, permission) VALUES (32, 'LEADS_TAB');
INSERT INTO permission(id, permission) VALUES (33, 'CALL_RECORDING_VIEW');
INSERT INTO permission(id, permission) VALUES (34, 'ENQUIRY_UPDATE_ASSIGNED');
INSERT INTO permission(id, permission) VALUES (35, 'ENQUIRY_UPDATE_TREATMENT');
INSERT INTO permission(id, permission) VALUES (36, 'ENQUIRY_UPDATE_LOCATION');

------NEW PERMISSION----------

INSERT INTO permission(id, permission) VALUES (37, 'INSURANCE_TAB');
INSERT INTO permission(id, permission) VALUES (38, 'LEADS_ENQUIRY_DATE_FIELD');
INSERT INTO permission(id, permission) VALUES (39, 'DOCTOR_AGREEMENT');
INSERT INTO permission(id, permission) VALUES (40, 'HOSPITAL_AGREEMENT');
INSERT INTO permission(id, permission) VALUES (41, 'LEADS_SL_NO_FIELD');
INSERT INTO permission(id, permission) VALUES (42, 'IP_OP_STATISTICS');
INSERT INTO permission(id, permission) VALUES (43, 'PATIENT_DETAIL_TAB');
INSERT INTO permission(id, permission) VALUES (44, 'INSURANCE_AGREEMENT_UPLOAD');
INSERT INTO permission(id, permission) VALUES (45, 'INSURANCE_POLICY_NO_FIELD');
INSERT INTO permission(id, permission) VALUES (46, 'STATISTICS_ORIGIN_FIELD');
INSERT INTO permission(id, permission) VALUES (47, 'PARTNER_PLATFORM_VIEW');
INSERT INTO permission(id, permission) VALUES (48, 'INSURANCE_SUB_TAB');
INSERT INTO permission(id, permission) VALUES (49, 'LOAN_DETAIL_SUB_TAB');
INSERT INTO permission(id, permission) VALUES (50, 'PATIENT_DOCS_SUB_TAB');
INSERT INTO permission(id, permission) VALUES (51, 'CAB_DETAIL_SUB_TAB');
INSERT INTO permission(id, permission) VALUES (52, 'CLICK_TO_CALL_BTN');
INSERT INTO permission(id, permission) VALUES (53, 'ENQUIRY_UPDATE_BTN');
INSERT INTO permission(id, permission) VALUES (54, 'HOSPITAL_UPDATE_BTN');
INSERT INTO permission(id, permission) VALUES (55, 'LOAN_DETAIL_SAVE_BTN');
INSERT INTO permission(id, permission) VALUES (56, 'LEAD_COMMENTS_FIELD');
INSERT INTO permission(id, permission) VALUES (57, 'LEAD_PAYMENT_FIELD');
INSERT INTO permission(id, permission) VALUES (58, 'INSURANCE_UPDATE_BUTTONS');
INSERT INTO permission(id, permission) VALUES (59, 'INSURANCE_DOC_BUTTONS');
INSERT INTO permission(id, permission) VALUES (60, 'INSURANCE_REJECTED_DOC_BUTTONS');
INSERT INTO permission(id, permission) VALUES (61, 'INSURANCE_APPROVED_DOC_BUTTONS');
INSERT INTO permission(id, permission) VALUES (62, 'LEAD_INTENT_FIELD');
INSERT INTO permission(id, permission,label) VALUES (63, 'INSURANCE_DETAILS_UPDATE','To view insurance details');
INSERT INTO permission(id, permission,label) VALUES (64, 'INSURANCE_DETAILS_VIEW','To view insurance details');
INSERT INTO permission(id, permission,label) VALUES (65, 'MYKARE_PLATFORM_VIEW','To view Mykare platform');
INSERT INTO permission(id, permission,label) VALUES (66, 'KARE_TRIP_PLATFORM_VIEW','To view Kare trip platform');
INSERT INTO permission(id, permission,label) VALUES (67, 'LEAD_MANAGEMENT_TAB','Assign leads to sales agent');
INSERT INTO permission(id, permission,label) VALUES (68, 'LEAD_TRANSFER_TAB','Transfer leads to sales agent');
INSERT INTO permission(id, permission,label) VALUES (69, 'BULK_MESSAGE_TAB','Send message to patients');
INSERT INTO permission(id, permission,label) VALUES (70, 'BLACKLIST_TAB','Blacklist user');
INSERT INTO permission(id, permission,label) VALUES (71, 'BUDDY_MANAGEMENT_TAB','Buddy management according to location');
INSERT INTO permission(id, permission,label) VALUES (72, 'SEND_FEEDBACK_LINK_BTN','To send feedback link to patient');

--UPDATE Label Query

update permission set label='Shows associate page' where id=1;
update permission set label='Shows mykare summary page' where id=2;
update permission set label='Download leads report' where id=3;
update permission set label='View Phone number of all leads' where id=4;
update permission set label='View and filter leads based on assigned to' where id=5;
update permission set label='View and filter leads based on sources' where id=6;
update permission set label='View leads partnership statistics' where id=7;
update permission set label='Show assigned to field on statistics' where id=8;
update permission set label='Add Hospital' where id=9;
update permission set label='View list of Hospitals' where id=10;
update permission set label='Delete Hospital' where id=11;
update permission set label='Add Doctor' where id=12;
update permission set label='View list of Doctors' where id=13;
update permission set label='Delete Doctor' where id=14;
update permission set label='View Ip/Op leads assigned' where id=15;
update permission set label='Download Ip/Op report' where id=16;
update permission set label='Bulk Message tab' where id=17;
update permission set label='View Partnership page' where id=18;
update permission set label='View Ip/Op leads page' where id=19;
update permission set label='View preventive care page' where id=20;
update permission set label='View second medical opinion page' where id=21;
update permission set label='View add on service page' where id=22;
update permission set label='View statistics page' where id=23;
update permission set label='To update enquiry' where id=24;
update permission set label='To save appointments details' where id=25;
update permission set label='To show hospitals details page' where id=26;
update permission set label='To show doctors details page' where id=27;
update permission set label='To create new leads' where id=28;
update permission set label='View statistics page' where id=29;
update permission set label='View settings page' where id=30;
update permission set label='View kare chat page' where id=31;
update permission set label='View leads details page' where id=32;
update permission set label='For call recording' where id=33;
update permission set label='Update sales agent of patients' where id=34;
update permission set label='Update Treatment of patients' where id=35;
update permission set label='Update Location of patients' where id=36;
update permission set label='View insurance page' where id=37;
update permission set label='View and filter leads based on enquiry date' where id=38;
update permission set label='View insurance page' where id=39;
update permission set label='Upload doctor agreement' where id=39;
update permission set label='Upload hospital agreement' where id=40;
update permission set label='Leads number field' where id=41;
update permission set label='To show Ip/Op statistics' where id=42;
update permission set label='To save patient details' where id=43;
update permission set label='Upload insurance agreement' where id=44;
update permission set label='To view insurance policy number' where id=45;
update permission set label='View statistics based on origin' where id=46;
update permission set label='View statistics based on origin' where id=47;
update permission set label='Save insurance details' where id=48;
update permission set label='To view Loan details' where id=49;
update permission set label='To save patient document details' where id=50;
update permission set label='To save patient cab details' where id=51;
update permission set label='Click to call button' where id=52;
update permission set label='To update enquiry' where id=53;
update permission set label='To update hospital details' where id=54;
update permission set label='To update loan details' where id=55;
update permission set label='To add comments of leads' where id=56;
update permission set label='To view payment mode' where id=57;
update permission set label='To show intent of leads' where id=62;
