-- insert values in user_permission table
insert into user_permission(id, name, label, role_id) values(1,'UPDATE_PATIENT','Update patient booking status',4);
insert into user_permission(id, name, label, role_id) values(2,'ADD_PATIENT','Add patient',4);
insert into user_permission(id, name, label, role_id) values(3,'ENTER_DETAILS','Enter facility details',3);
insert into user_permission(id, name, label, role_id) values(4,'ADD_DOCTORS','Add Doctors',3);
insert into user_permission(id, name, label, role_id) values(5,'CREATE_PACKAGES','Create health packages',3);
insert into user_permission(id, name, label, role_id) values(6,'ADD_MEMBERS','Add your team members',3);
insert into user_permission(id, name, label, role_id) values(7,'VIEW_BOOKINGS','View bookings',4);
insert into user_permission(id, name, label, role_id) values(8,'UPDATE_STATUS','Update patient booking status',2);
insert into user_permission(id, name, label, role_id) values(9,'ADD_PATIENT','Add patient',2);
insert into user_permission(id, name, label, role_id) values(10,'ENTER_DETAILS','Enter facility details',2);
insert into user_permission(id, name, label, role_id) values(11,'ADD_DOCTORS','Add Doctors',2);
insert into user_permission(id, name, label, role_id) values(12,'CREATE_PACKAGES','Create health packages',2);
insert into user_permission(id, name, label, role_id) values(13,'ADD_MEMBERS','Add your team members',2);
insert into user_permission(id, name, label, role_id) values(14,'VIEW_BOOKINGS','View bookings',2);
insert into user_permission(id, name, label, role_id) values(15,'ADD_ENQUIRIES','Add enquiries',2);
insert into user_permission(id, name, label, role_id) values(16,'GENERATE_REPORTS','Generate reports',2);
insert into user_permission(id, name, label, role_id) values(17,'UPDATE_STATUS','Update patient booking status',1);
insert into user_permission(id, name, label, role_id) values(18,'ADD_PATIENT','Add patient',1);
insert into user_permission(id, name, label, role_id) values(19,'ENTER_DETAILS','Enter facility details',1);
insert into user_permission(id, name, label, role_id) values(20,'ADD_DOCTORS','Add Doctors',1);
insert into user_permission(id, name, label, role_id) values(21,'CREATE_PACKAGES','Create health packages',1);
insert into user_permission(id, name, label, role_id) values(22,'ADD_MEMBERS','Add your team members',1);
insert into user_permission(id, name, label, role_id) values(23,'VIEW_BOOKINGS','View bookings',1);
insert into user_permission(id, name, label, role_id) values(24,'ADD_ENQUIRIES','Add enquiries',1);
insert into user_permission(id, name, label, role_id) values(25,'GENERATE_REPORTS','Generate reports',1);
insert into user_permission(id, name, label, role_id) values(26,'APPROVE_FACILITY','Approve facility',1);
insert into user_permission(id, name, label, role_id) values(27,'APPROVE_CENTER','Approve center',1);
insert into user_permission(id, name, label, role_id) values(28,'APPROVE_ADMIN','Approve admin',1);
insert into user_permission(id, name, label, role_id) values(29,'VIEW_FACILITY','View facility',1);
insert into user_permission(id, name, label, role_id) values(30,'VIEW_CENTER','View center',1);
insert into user_permission(id, name, label, role_id) values(31,'VIEW_ADMIN','View admin',1);
