package com.masjid.crm.service;

import com.masjid.crm.Util.FinancialAccountFactory;
import com.masjid.crm.dto.request.FinancialAccountRequest;
import com.masjid.crm.dto.response.FinancialAccountListResponse;
import com.masjid.crm.dto.response.FinancialSummaryResponse;
import com.masjid.crm.entity.FinancialAccount;
import com.masjid.crm.model.FinancialCategory;
import com.masjid.crm.model.FinancialSource;
import com.masjid.crm.model.PaymentStatus;
import com.masjid.crm.model.TransactionType;
import com.masjid.crm.repository.FinancialAccountRepository;
import com.masjid.crm.specification.FinancialAccountSpecification;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import java.util.Date;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;

@Service
public class FinancialAccountService {

    @Autowired
    private FinancialAccountRepository repository;

    public FinancialAccount save(FinancialAccountRequest request) {
        FinancialAccount entity;

        if (request.getId() != null) {
            entity = repository.findById(request.getId())
                    .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                            "FinancialAccount not found"));
            if (isAutoGenerated(entity)) {
                throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                        "This entry is auto-generated from " + entity.getSourceType()
                                + ". Edit it on the source record instead.");
            }
        } else {
            entity = new FinancialAccount();
            entity.setSourceType(FinancialSource.MANUAL);
        }

        entity.setTransactionType(request.getTransactionType());
        entity.setCategory(request.getCategory());
        entity.setAmount(request.getAmount());
        entity.setTransactionDate(request.getTransactionDate());
        entity.setPaymentMethod(request.getPaymentMethod());
        entity.setReferenceNumber(request.getReferenceNumber());
        entity.setPayerOrPayeeName(request.getPayerOrPayeeName());
        entity.setDescription(request.getDescription());
        entity.setPaymentStatus(request.getPaymentStatus() == null
                ? PaymentStatus.RECEIVED
                : request.getPaymentStatus());

        return repository.save(entity);
    }

    public void delete(Long id) {
        FinancialAccount entity = repository.findById(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                        "FinancialAccount not found"));
        if (isAutoGenerated(entity)) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                    "This entry is auto-generated from " + entity.getSourceType()
                            + ". To remove it, cancel the source " + entity.getSourceType()
                            + " record instead.");
        }
        repository.delete(entity);
    }

    private boolean isAutoGenerated(FinancialAccount entity) {
        return entity.getSourceType() != null && entity.getSourceType() != FinancialSource.MANUAL;
    }

    public FinancialAccount updatePaymentStatus(Long id, PaymentStatus newStatus) {
        if (newStatus == null) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Payment status is required");
        }
        FinancialAccount entity = repository.findById(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
                        "FinancialAccount not found: " + id));

        if (isAutoGenerated(entity)) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                    "This entry is auto-generated from " + entity.getSourceType()
                            + ". Update the status on the source record instead.");
        }

        PaymentStatus current = entity.getPaymentStatus();
        if (current == PaymentStatus.CANCELLED) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                    "Cancelled entries cannot be modified");
        }
        if (current == PaymentStatus.RECEIVED && newStatus == PaymentStatus.PENDING) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST,
                    "A received payment cannot be moved back to pending");
        }

        entity.setPaymentStatus(newStatus);
        return repository.save(entity);
    }

    public FinancialAccountListResponse filter(FinancialAccountRequest request) {
        int pageNo = request.getPageNo() == null ? 0 : request.getPageNo();
        int pageSize = request.getPageSize() == null ? 10 : request.getPageSize();

        Pageable pageable = PageRequest.of(pageNo, pageSize,
                Sort.by("transactionDate").descending().and(Sort.by("id").descending()));
        Specification<FinancialAccount> spec = FinancialAccountSpecification.filter(request);
        Page<FinancialAccount> page = repository.findAll(spec, pageable);
        return FinancialAccountFactory.toListResponse(page, page.getTotalElements());
    }

    public FinancialSummaryResponse summary(Date fromDate, Date toDate) {
        FinancialAccountRequest req = new FinancialAccountRequest();
        req.setFromDate(fromDate);
        req.setToDate(toDate);
        Specification<FinancialAccount> spec = FinancialAccountSpecification.filter(req);
        List<FinancialAccount> all = repository.findAll(spec);

        double totalIncome = 0.0;
        double totalExpense = 0.0;
        double pendingIncome = 0.0;
        double pendingExpense = 0.0;
        Map<FinancialCategory, Double> incomeByCat = new EnumMap<>(FinancialCategory.class);
        Map<FinancialCategory, Double> expenseByCat = new EnumMap<>(FinancialCategory.class);

        for (FinancialAccount f : all) {
            if (f.getAmount() == null || f.getTransactionType() == null) continue;
            if (f.getPaymentStatus() == PaymentStatus.CANCELLED) continue;

            boolean isPending = f.getPaymentStatus() == PaymentStatus.PENDING;

            if (f.getTransactionType() == TransactionType.INCOME) {
                if (isPending) {
                    pendingIncome += f.getAmount();
                } else {
                    totalIncome += f.getAmount();
                    if (f.getCategory() != null) {
                        incomeByCat.merge(f.getCategory(), f.getAmount(), Double::sum);
                    }
                }
            } else if (f.getTransactionType() == TransactionType.EXPENSE) {
                if (isPending) {
                    pendingExpense += f.getAmount();
                } else {
                    totalExpense += f.getAmount();
                    if (f.getCategory() != null) {
                        expenseByCat.merge(f.getCategory(), f.getAmount(), Double::sum);
                    }
                }
            }
        }

        return FinancialSummaryResponse.builder()
                .totalIncome(totalIncome)
                .totalExpense(totalExpense)
                .balance(totalIncome - totalExpense)
                .pendingIncome(pendingIncome)
                .pendingExpense(pendingExpense)
                .incomeByCategory(incomeByCat)
                .expenseByCategory(expenseByCat)
                .build();
    }
}
